### ISSUE TITLE
Convert the release playbook into a Basecamp project template

### ISSUE THREAD

**Issue by andrewsanchez** [qiime2/distributions#21]
**Improvement Description**
Provide a reusable [Basecamp project template](https://3.basecamp-help.com/article/66-templates#creating-a-new-project-template) that can be used for each release, complete with all of the niceties that Basecamp projects have to offer.

**Current Behavior**
The release playbook is presently in the form of a [Google Document](https://docs.google.com/document/d/1Zmz0ShfvsDDciWSEXpgMlSMM45fQIXkXh-AQcbXsH4k/edit?usp=sharing).

**Proposed Behavior**
- Pre-populated to do lists.
- Message board(s), as needed
- A campfire
- Possibly a schedule
- Hill charts

**Comments**
1. Perhaps this can be generated as a by-product of the next release.

**Comment by thermokarst** [comment]
Please note, the Google Doc linked to above is private - this is an internal procedure at the moment.
